chore: check if AIGateway CRD exists in the cluster before creating a count provider
Kong/kong-operator pull request #360
Opened 2024-06-20 18:53 UTC by pmalek

**What this PR does / why we need it**:

- Prevent users being confused by the error message being logged when AIGateway count provider fails to get created

  Related issue: #297 

- Additionally this creates a CRD guard so that when user requests AIGateway controller but the CRD is not in place then controller exits with an error.

- This also fixes the aigateway reports in telemetry. For some reason (probably due to the incorrect pluralized version `aigatewies` used in AIGateway GVR).

  The reports now include the AIGateway entry:
  
  ```
  report: <14>signal=gateway-operator-start;hn=P-Maek-MBP;uptime=0;v=NOT_SET;k8s_aigateways_count=1;k8s_controlplanes_count=0;k8s_controlplanes_requested_replicas_count=0;k8s_dataplanes_count=0;k8s_dataplanes_requested_replicas_count=0;k8s_gatewayclasses_count=1;k8s_gateways_count=0;k8s_httproutes_count=0;k8s_nodes_count=1;k8s_pods_count=14;k8s_referencegrants_count=0;k8s_services_count=4;k8s_standalone_controlplanes_count=0;k8s_standalone_dataplanes_count=0;k8s_arch=linux/arm64;k8s_provider=kind;k8sv=v1.30.0;k8sv_semver=v1.30.0;
  ```

### Special notes for your reviewer:

For whatever reason the tests do not allow the full suite to pass as it used to. It's most likely relate to the pluralising issue in k8s: https://github.com/kubernetes/client-go/issues/1082

2024-06-20 23:07 UTC, rainest requested changes

2024-06-20 23:07 UTC, rainest commented on internal/telemetry/telemetry_test.go
> +			// gateway-operator.konghq.com/v1alpha1, Resource=aigateways out of map
```suggestion
			// See NewSimpleDynamicClientWithCustomListKinds:
			// https://pkg.go.dev/k8s.io/client-go/dynamic/fake#NewSimpleDynamicClientWithCustomListKinds
			// or register the list into the scheme:
```

2024-06-20 23:07 UTC, rainest commented on internal/telemetry/telemetry_test.go
> +			// gateway-operator.konghq.com/v1alpha1, Resource=aigateways out of map
```suggestion
			// See NewSimpleDynamicClientWithCustomListKinds:
			// https://pkg.go.dev/k8s.io/client-go/dynamic/fake#NewSimpleDynamicClientWithCustomListKinds
			// or register the list into the scheme:
```

2024-06-21 03:16 UTC, randmonkey commented
Does this PR need a changelog entry? I think changes on the metrics should need one.

2024-06-21 09:47 UTC, pmalek commented on internal/telemetry/telemetry_test.go
> +			// or register the list into the scheme:
The list is also registered into the scheme https://github.com/Kong/gateway-operator/blob/3876430e09e61edce58bd8464989e33236bd1872/api/v1alpha1/aigateway_types.go#L254-L255. So it's not only that.

2024-06-21 11:16 UTC, pmalek commented
> Does this PR need a changelog entry?

@randmonkey No need for changelog, this is not user facing.

2024-06-21 19:13 UTC, rainest approved these changes

2024-06-21 20:17 UTC, merged