feat(dp): handle creating PodDisruptionBudget for deployment
Kong/kong-operator pull request #464
Opened 2024-08-07 06:57 UTC by czeslavo

**What this PR does / why we need it**:

Adds PodDisruptionBudget reconciliation for DataPlanes.

**Which issue this PR fixes**

Fixes #

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2024-08-07 13:16 UTC, pmalek requested changes

2024-08-07 13:16 UTC, pmalek commented on pkg/utils/kubernetes/reduce/reduce.go
> +		if err := k8sClient.Delete(ctx, &hpa); client.IgnoreNotFound(err) != nil {
```suggestion
	for _, pdb := range filter(pdbs) {
		pdb := pdb
		if err := k8sClient.Delete(ctx, &pdb); client.IgnoreNotFound(err) != nil {
```

2024-08-07 13:16 UTC, pmalek commented on pkg/utils/kubernetes/reduce/reduce.go
> +// +kubebuilder:rbac:groups=policy,resources=poddistruptionbudgets,verbs=delete
Typo: 

```suggestion
// +kubebuilder:rbac:groups=policy,resources=poddisruptionbudgets,verbs=delete
```

2024-08-07 13:16 UTC, pmalek commented on config/rbac/role/role.yaml
> +  - poddistruptionbudgets
Type caused by https://github.com/Kong/gateway-operator/pull/464/files#diff-59fdb2373e0a4c4eb9f34c451f482c01b9ef65679ccfd7290152a4488da21869R169.

This needs to be changed at the source and regenerated.

2024-08-07 13:16 UTC, pmalek commented on controller/dataplane/owned_resources.go
> +		return op.Noop, nil, fmt.Errorf("failed listing PodDisruptionBudgets for DataPlane %s/%s: %w", dataplane.Namespace, dataplane.Name, err)
Consider created a `nn` variable set to `client.ObjectKeyFromObject(dataplane)` and then using that in places where you use: `dataplane.Namespace, dataplane.Name`.

2024-08-08 09:01 UTC, pmalek commented on pkg/utils/kubernetes/reduce/filters.go
> +func FilterPodDisruptionBudgets(pdbs []policyv1.PodDisruptionBudget) []policyv1.PodDisruptionBudget {
Can we add UTs for this in `pkg/utils/kubernetes/reduce/filters_test.go`?

2024-08-08 09:01 UTC, pmalek commented on pkg/utils/kubernetes/reduce/reduce.go
> +type PDBFilterFunc func(hpas []policyv1.PodDisruptionBudget) []policyv1.PodDisruptionBudget
🙃 

```suggestion
type PDBFilterFunc func(pdbs []policyv1.PodDisruptionBudget) []policyv1.PodDisruptionBudget
```

We might as well mention in the type comment what return value can be used for (is this the slice of entities to remove or those are the ones that have been removed?)

2024-08-08 09:01 UTC, pmalek commented on pkg/utils/kubernetes/resources/pdbs.go
> +	labels[consts.OperatorLabelSelector] = dataplane.Status.Selector
I believe this is good but have you tested this with `DataPlane`s using BG rollouts?

2024-08-08 09:01 UTC, pmalek commented on pkg/utils/test/predicates.go
> +// that can be used to check if a DataPlane has a PodDisruptionBudget.
Can we expand this comment to explain what `has` means here? Does that mean that a PDB is created in the cluster? That it has all the required metadata (ownership, labels etc)?

2024-08-08 12:00 UTC, czeslavo commented on pkg/utils/kubernetes/resources/pdbs.go
> +	labels[consts.OperatorLabelSelector] = dataplane.Status.Selector
I verified that during a BG rollout, the PDB target switches between the deployments after promotion (`status.selector` is updated to always point to an active deployment).

2024-08-08 12:20 UTC, pmalek approved these changes

2024-08-08 17:02 UTC, pmalek commented
The E2E are failing due to policy rules not being in place in the helm chart (a sad reality of chicken and egg problem in tests :/)

```
2024-08-08T14:05:16.22262256Z stderr F W0808 14:05:16.222529       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:16.222648388Z stderr F E0808 14:05:16.222563       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:16.319688827Z stderr F {"level":"info","ts":"2024-08-08T14:05:16Z","msg":"Starting workers","controller":"gatewayclass","controllerGroup":"gateway.networking.k8s.io","controllerKind":"GatewayClass","worker count":1}
2024-08-08T14:05:17.816154465Z stderr F W0808 14:05:17.816064       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:17.816173621Z stderr F E0808 14:05:17.816095       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:19.759403497Z stderr F W0808 14:05:19.759318       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:19.759425408Z stderr F E0808 14:05:19.759349       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:25.542095916Z stderr F W0808 14:05:25.542015       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:25.542113007Z stderr F E0808 14:05:25.542046       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:37.972238936Z stderr F W0808 14:05:37.972165       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:37.972260346Z stderr F E0808 14:05:37.972194       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:51.355521461Z stderr F W0808 14:05:51.355402       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:05:51.355544163Z stderr F E0808 14:05:51.355438       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:06:40.474584374Z stderr F W0808 14:06:40.474497       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:06:40.474609751Z stderr F E0808 14:06:40.474523       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:5670ced5-4151-4c84-8449-a08266eb6387:controller-manager" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
2024-08-08T14:07:16.212545541Z stderr F {"level":"error","ts":"2024-08-08T14:07:16Z","msg":"Could not wait for Cache to sync","controller":"dataplane","controllerGroup":"gateway-operator.konghq.com","controllerKind":"DataPlane","error":"failed to wait for dataplane caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.DataPlane","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:203\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:229\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/manager/runnable_group.go:226"}
```

I'm not sure if we want to solve it differently than adding rules from this PR to helm chart already.

We could be tempted to patch the policy rules in tests but that can be error prone.

I'm curious to your thoughts on this.

2024-08-09 07:24 UTC, czeslavo commented
> We could be tempted to patch the policy rules in tests but that can be error prone.

Yeah, I agree that's better to add the rules already to the helm chart. At least by having these E2Es failing, it gives us direct feedback on the missing pieces and we're fixing them in the right place. By patching them, we'd still have to remember to add the rules to the chart eventually. 

Adding them and releasing straight away: https://github.com/Kong/charts/pull/1114

2024-08-09 08:36 UTC, merged