Update Chart.yaml
Kong/kong-operator pull request #58
Opened 2021-03-31 05:07 UTC by jose-j01

appVersion should be of type string but it's of type float64

2021-03-31 05:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong-operator?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong-operator?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong-operator?pullRequest=58) it.</sub>

2021-03-31 13:32 UTC, mflendrich requested changes
Thanks for this catch.

~Please change the target branch of this PR to `next`, though - `main` is for already released versions that we don't want to modify.~ see Travis's comment below.

2021-04-01 22:32 UTC, rainest commented
How did you encounter this in practice/what failed?

This change should go upstream to https://github.com/Kong/charts, since we don't want the plain chart and chart in the operator to diverge.

While YAML's helpful type coercions are a common problem, I'm curious how we didn't get a report for a similar issue on the chart repo earlier--it's had an appVersion that can convert to float for quite some time. I haven't encountered complaints from Helm (embedded within the operator or otherwise) about it, but it's possible there's logic in Helm that normally ignores such issues, but not with some specific workflows.

2021-04-20 16:33 UTC, rainest commented
https://github.com/Kong/charts/pull/343 handled this upstream. Next chart release, which we'll also want to roll an operator release for, is pending a migration of our Enterprise Kong images off Bintray.

2021-04-20 16:33 UTC, closed without merging