chore: prepare 1.4.0-rc.0
Kong/kong-operator pull request #741
Opened 2024-10-11 15:48 UTC by pmalek

**What this PR does / why we need it**:

Preparing changelog for `1.4.0-rc.0`

2024-10-12 02:19 UTC, randmonkey approved these changes

2024-10-12 11:38 UTC, tao12345666333 approved these changes

2024-10-14 10:03 UTC, randmonkey commented
Looks like the release date need updating. @pmalek

2024-10-17 09:57 UTC, randmonkey requested changes, later dismissed
Release date cannot be 10-11

2024-10-23 12:24 UTC, merged